[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "true"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyDOCAbC123dEf456GhI789jKl012-MnO,AIza...."
  SECRETS_SCAN_OMIT_PATHS = "node_modules/@firebase/**"
