export type ShorelineSegmentReason =
  | 'same_continuous_beachfront'
  | 'same_cove_or_micro_bay'
  | 'same_village_bay';

export interface ShorelineSegment {
  id: string;
  regionId: string;
  beachIds: number[];
  reason: ShorelineSegmentReason;
  notes: string;
}

export const SHORELINE_SEGMENTS: ShorelineSegment[] = [
  {
    id: 'kea-vlanti-kaliskia-front',
    regionId: 'south-aegean-kea',
    beachIds: [1806, 1811],
    reason: 'same_continuous_beachfront',
    notes: 'Vlanti and Kaliskia are adjacent southeast-facing east/southeast Kea records; the broader Poles/Mavia cluster is not propagated because geospatial exposure differs.',
  },
  {
    id: 'kea-vroskopos-kalamitsi-kalogiros-front',
    regionId: 'south-aegean-kea',
    beachIds: [1807, 1809, 1812],
    reason: 'same_continuous_beachfront',
    notes: 'Vroskopos, Kalamitsi, and Kalogiros are neighboring west-facing west Kea records; Pisses is kept separate because bay exposure differs.',
  },
  {
    id: 'kea-koundouros-freas-front',
    regionId: 'south-aegean-kea',
    beachIds: [1815, 1834],
    reason: 'same_village_bay',
    notes: 'Koundouros and Freas are close west-facing Koundouros bay records; other nearby coves are kept separate because exposure differs.',
  },
  {
    id: 'kea-lygia-chyliamodou-front',
    regionId: 'south-aegean-kea',
    beachIds: [1818, 1835],
    reason: 'same_village_bay',
    notes: 'Lygia and Chyliamodou are close west-facing Koundouros bay records and remain separate from Koundouros/Freas until exposure evidence matches.',
  },
  {
    id: 'kea-mavrampeli-xyla-front',
    regionId: 'south-aegean-kea',
    beachIds: [1820, 1823],
    reason: 'same_continuous_beachfront',
    notes: 'Mavrampeli and Xyla are nearby northwest-facing west/northwest Kea records; difficult road access remains separately scored.',
  },
  {
    id: 'kythnos-koloveloni-petrousa-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1878, 1889],
    reason: 'same_continuous_beachfront',
    notes: 'Koloveloni and Petrousa are neighboring south-facing south Kythnos records; Agios Dimitrios is kept separate because west-wind map exposure differs.',
  },
  {
    id: 'kythnos-agios-nikolaos-nika-skylou-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1860, 1866, 1887, 1895],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Nikolaos, Antonides, Nika, and Skylou are close southeast-facing southeast Kythnos records; dirt-road difficulty remains separately scored.',
  },
  {
    id: 'kythnos-agios-stefanos-lagkousi-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1861, 1864, 1869, 1880],
    reason: 'same_village_bay',
    notes: 'Agios Stefanos, Agkoritsa, Vasiliko, and Lagkousi are neighboring south-facing east-coast bay records; boat-only access remains a top-pick blocker where relevant.',
  },
  {
    id: 'kythnos-aosa-kouri-zogkaki-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1868, 1873, 1879],
    reason: 'same_continuous_beachfront',
    notes: 'Aosa, Zogkaki, and Kouri are close southeast-facing east Kythnos records with similar practical exposure behavior.',
  },
  {
    id: 'kythnos-agios-sostis-potamia-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1862, 1874, 1891],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Sostis, Kavourocheri, and Potamia are neighboring east-facing northeast Kythnos records; access remains separate.',
  },
  {
    id: 'kythnos-agia-irini-maroula-skinari-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1863, 1884],
    reason: 'same_continuous_beachfront',
    notes: 'Agia Irini and Maroula are nearby east-facing northeast Kythnos records; Skinari is kept outside because map-exposure validation shows a stricter local behavior.',
  },
  {
    id: 'kythnos-kaki-maria-kalo-livadi-levkes-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1875, 1876, 1881],
    reason: 'same_continuous_beachfront',
    notes: 'Kaki Maria, Kalo Livadi, and Levkes are neighboring east-facing east Kythnos records with similar shoreline behavior.',
  },
  {
    id: 'kythnos-gaidouromantra-markouli-si-mou-si-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1871, 1883, 1892],
    reason: 'same_continuous_beachfront',
    notes: 'Gaidouromantra, Markouli, and Si Mou Si are neighboring southeast-facing south/east Kythnos records; access difficulty remains separate.',
  },
  {
    id: 'kythnos-galazia-kastella-flampouria-pontikia-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1870, 1877, 1890, 1897],
    reason: 'same_continuous_beachfront',
    notes: 'Galazia Akti, Kastella, Pontikia, and Flampouria are west/northwest-facing west Kythnos records; individual access confidence remains separate.',
  },
  {
    id: 'kythnos-livadaki-mikro-livadaki-front',
    regionId: 'south-aegean-kythnos',
    beachIds: [1882, 1886],
    reason: 'same_cove_or_micro_bay',
    notes: 'Livadaki and Mikro Livadaki are adjacent northeast-facing records; difficult hiking access remains a top-pick blocker.',
  },
  {
    id: 'serifos-agios-sostis-psili-ammos-lia-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2071, 2072, 2086, 2094],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Sostis, Ai Giannis, Lia, and Psili Ammos are neighboring east-facing Serifos records; access and organized-service differences remain separate.',
  },
  {
    id: 'serifos-livadakia-karavi-alevrakia-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2073, 2083, 2087],
    reason: 'same_continuous_beachfront',
    notes: 'Alevrakia, Karavi, and Livadakia are close southeast-facing port-side records; Avlomonas is kept outside due to different south-facing bay behavior.',
  },
  {
    id: 'serifos-vagia-ganema-koutalas-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2076, 2078, 2085],
    reason: 'same_village_bay',
    notes: 'Vagia, Ganema, and Koutalas are neighboring southwest-facing south Serifos records; amenities and road access remain separate.',
  },
  {
    id: 'serifos-achladi-kalogeros-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2075, 2081],
    reason: 'same_continuous_beachfront',
    notes: 'Achladi and Kalogeros are adjacent south/southeast-facing west-coast records; boat-only access remains a separate top-pick blocker.',
  },
  {
    id: 'serifos-vorino-mesiano-platys-gialos-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2077, 2090, 2091],
    reason: 'same_village_bay',
    notes: 'Vorino, Mesiano, and Platys Gialos are adjacent north-facing north Serifos bay records.',
  },
  {
    id: 'serifos-sykamia-gialoudi-karavas-front',
    regionId: 'south-aegean-serifos',
    beachIds: [2079, 2082, 2093],
    reason: 'same_continuous_beachfront',
    notes: 'Gialoudi, Karavas, and Sykamia are neighboring north/northwest-facing west-north Serifos records; Skala is kept separate because east-wind exposure differs.',
  },
  {
    id: 'sifnos-faros-apokofto-fasolou-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2095, 2099, 2106, 2112, 2113],
    reason: 'same_village_bay',
    notes: 'Apokofto, Vlycho, Saoures, Faros, and Fasolou are neighboring southeast-facing Faros/Chrysopigi records; village services and access remain separately scored.',
  },
  {
    id: 'sifnos-platys-gialos-lazarou-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2102, 2104],
    reason: 'same_continuous_beachfront',
    notes: 'Lazarou and Platys Gialos are adjacent southeast-facing south Sifnos records; organized-service differences remain separate.',
  },
  {
    id: 'sifnos-vathi-tsopou-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2097, 2110],
    reason: 'same_village_bay',
    notes: 'Vathi and Tsopou are neighboring southwest-facing Vathi bay records; access and amenities remain separately scored.',
  },
  {
    id: 'sifnos-kamares-spilia-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2101, 2108],
    reason: 'same_village_bay',
    notes: 'Kamares and Spilia are adjacent west-facing port-bay records and should not diverge without a specific harbor morphology reason.',
  },
  {
    id: 'sifnos-artimoni-vroulidia-cherronisos-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2096, 2100, 2114],
    reason: 'same_continuous_beachfront',
    notes: 'Artimoni, Vroulidia, and Cherronisos are nearby north-Sifnos southwest-facing records; road access and organization remain separate.',
  },
  {
    id: 'sifnos-toso-nero-tsocha-front',
    regionId: 'south-aegean-sifnos',
    beachIds: [2109, 2111],
    reason: 'same_continuous_beachfront',
    notes: 'Toso Nero and Tsocha are nearby west-facing records; boat-only access remains a top-pick blocker where relevant.',
  },
  {
    id: 'ios-plakotos-karatzas-kampaki-front',
    regionId: 'south-aegean-ios',
    beachIds: [1756, 1758, 1769],
    reason: 'same_continuous_beachfront',
    notes: 'Gero Aggeli, Plakotos, and Karatzas are neighboring northwest-facing north Ios records; name/duplicate risk and access confidence remain separately audited.',
  },
  {
    id: 'ios-psathi-northeast-front',
    regionId: 'south-aegean-ios',
    beachIds: [1764, 1791, 1794, 1803],
    reason: 'same_continuous_beachfront',
    notes: 'Vathy Rema, Roussou, Sofias Avlaki, and Psathi sit on the same practical northeast/east Ios coast; amenities and road access remain separate.',
  },
  {
    id: 'ios-almyros-diammoudia-lorentzaina-front',
    regionId: 'south-aegean-ios',
    beachIds: [1762, 1766, 1776],
    reason: 'same_continuous_beachfront',
    notes: 'Almyros, Diammoudia, and Lorentzaina are nearby west-facing records with similar practical exposure behavior.',
  },
  {
    id: 'ios-mylopotas-kolitsani-valmas-front',
    regionId: 'south-aegean-ios',
    beachIds: [1765, 1771, 1773, 1780],
    reason: 'same_continuous_beachfront',
    notes: 'Valmas, Katsiveli, Kolitsani, and Mylopotas are adjacent southwest-facing Chora/Mylopotas records; resort popularity and access remain separate.',
  },
  {
    id: 'ios-koumpara-tzamaria-front',
    regionId: 'south-aegean-ios',
    beachIds: [1774, 1795],
    reason: 'same_continuous_beachfront',
    notes: 'Koumpara and Tzamaria are nearby south/southwest-facing port-side records with similar map exposure behavior.',
  },
  {
    id: 'ios-klima-pikri-nero-sapounochoma-front',
    regionId: 'south-aegean-ios',
    beachIds: [1772, 1789, 1793],
    reason: 'same_continuous_beachfront',
    notes: 'Klima, Pikri Nero, and Sapounochoma are neighboring southwest-facing remote records; difficult access must still block top-pick promotion.',
  },
  {
    id: 'ios-kalamos-papas-plakes-front',
    regionId: 'south-aegean-ios',
    beachIds: [1767, 1785, 1790],
    reason: 'same_continuous_beachfront',
    notes: 'Kalamos, Papas, and Plakes are nearby east/southeast Ios records with related shoreline behavior; boat/difficult access remains separate.',
  },
  {
    id: 'ios-manganari-tris-klisies-front',
    regionId: 'south-aegean-ios',
    beachIds: [1777, 1778, 1798, 1799, 1800, 1802],
    reason: 'same_continuous_beachfront',
    notes: 'Louka Avlaki, Manganari, the Tris Klisies records, and Chalara sit on the broader southeast south-Ios beachfront system; access and individual cove confidence remain separate.',
  },
  {
    id: 'ios-santoriniko-trypiti-front',
    regionId: 'south-aegean-ios',
    beachIds: [1792, 1801],
    reason: 'same_continuous_beachfront',
    notes: 'Santoriniko and Trypiti are neighboring south/southwest remote records; Antonarou is kept separate because east-wind exposure differs.',
  },
  {
    id: 'ios-manousou-pepa-front',
    regionId: 'south-aegean-ios',
    beachIds: [1779, 1783],
    reason: 'same_cove_or_micro_bay',
    notes: 'Manousou and Pepa are adjacent southwest-facing boat-only records and should render consistently while remaining blocked from mainstream top picks.',
  },
  {
    id: 'santorini-perissa-perivolos-agios-georgios-front',
    regionId: 'south-aegean-santorini',
    beachIds: [2068, 2067, 2057],
    reason: 'same_continuous_beachfront',
    notes: 'Perissa, Perivolos, and Agios Georgios form the main southeast Santorini beach-front; resort amenities and access remain separately scored.',
  },
  {
    id: 'santorini-vlychada-front',
    regionId: 'south-aegean-santorini',
    beachIds: [2058, 2060],
    reason: 'same_continuous_beachfront',
    notes: 'Vlychada and Gymnistiki Paralia Vlychada are adjacent south-facing records; hiking/naturist context remains separate from exposure consistency.',
  },
  {
    id: 'santorini-red-white-south-front',
    regionId: 'south-aegean-santorini',
    beachIds: [2062, 2063],
    reason: 'same_continuous_beachfront',
    notes: 'Kokkini Paralia and Levki Paralia are neighboring south-facing caldera-side records; difficult/boat-only access must still block top-pick promotion.',
  },
  {
    id: 'mykonos-town-megali-ammos-agia-anna-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1961, 1946, 1939],
    reason: 'same_continuous_beachfront',
    notes: 'Megali Ammos, Agios Charalampos, and Agia Anna are neighboring northwest-facing Chora-side records; dirt-road/access handling remains separate.',
  },
  {
    id: 'mykonos-paragka-kalamopodi-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1941, 1966, 1951],
    reason: 'same_continuous_beachfront',
    notes: 'Agia Anna Paragkas, Paragka, and Kalamopodi form a close south-facing resort-front; Platys Gialos and Psarrou are kept separate because west-wind exposure differs.',
  },
  {
    id: 'mykonos-elia-agrari-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1950, 1949, 1947],
    reason: 'same_continuous_beachfront',
    notes: 'Elia, Gymnistiki Paralia Elias, and Agrari are adjacent south-facing records with near-identical orientation.',
  },
  {
    id: 'mykonos-kalafati-agia-anna-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1952, 1940],
    reason: 'same_village_bay',
    notes: 'Kalafati and Agia Anna Kalafatis are neighboring southeast/south-facing Kalafatis bay records with similar exposure behavior.',
  },
  {
    id: 'mykonos-agios-stefanos-choulakia-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1944, 1978],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Stefanos and Choulakia are nearby southwest-facing northwest-coast records with similar practical exposure behavior.',
  },
  {
    id: 'mykonos-panormos-agios-sostis-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1965, 1945],
    reason: 'same_village_bay',
    notes: 'Panormos and Agios Sostis are north/northeast-facing Panormos-bay records; amenities and popularity remain separate.',
  },
  {
    id: 'mykonos-fokos-mersini-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1977, 1962],
    reason: 'same_cove_or_micro_bay',
    notes: 'Fokos and Mersini are neighboring north-facing remote records; difficult/passable road access must not become a top-pick shortcut.',
  },
  {
    id: 'mykonos-merchia-sokratis-front',
    regionId: 'south-aegean-mykonos',
    beachIds: [1963, 1967],
    reason: 'same_continuous_beachfront',
    notes: 'Merchia and Sokratis are nearby northeast-facing records with matching shoreline behavior; access confidence remains separate.',
  },
  {
    id: 'syros-megas-gialos-ampela-lagkonaki-front',
    regionId: 'south-aegean-syros',
    beachIds: [2140, 2129, 2137],
    reason: 'same_continuous_beachfront',
    notes: 'Megas Gialos, Ampela, and Lagkonaki are neighboring southeast south-coast Syros records with near-matching shoreline facing; amenities/access remain separate.',
  },
  {
    id: 'syros-achladi-vari-front',
    regionId: 'south-aegean-syros',
    beachIds: [2131, 2143],
    reason: 'same_village_bay',
    notes: 'Achladi and Vari are adjacent southeast-facing Vari bay records and should not diverge without a specific local morphology reason.',
  },
  {
    id: 'syros-kini-loto-front',
    regionId: 'south-aegean-syros',
    beachIds: [2136, 2146],
    reason: 'same_village_bay',
    notes: 'Kini and Loto are neighboring northwest-facing Kini bay records; popularity and amenities remain separate from exposure consistency.',
  },
  {
    id: 'syros-delfini-varvarousa-front',
    regionId: 'south-aegean-syros',
    beachIds: [2135, 2133],
    reason: 'same_continuous_beachfront',
    notes: 'Delfini and Varvarousa are close west/northwest coast records with similar open-sector behavior; difficult-access handling remains separate.',
  },
  {
    id: 'syros-lia-marmari-megas-lakos-front',
    regionId: 'south-aegean-syros',
    beachIds: [2138, 2139, 2141],
    reason: 'same_continuous_beachfront',
    notes: 'Lia, Marmari, and Megas Lakos are close northwest Syros west-facing records with near-matching shoreline facing; confidence is map-consistency support only.',
  },
  {
    id: 'syros-grammata-amerikanou-front',
    regionId: 'south-aegean-syros',
    beachIds: [2134, 2128],
    reason: 'same_cove_or_micro_bay',
    notes: 'Grammata and Amerikanou are neighboring far-northwest west-facing records; boat/difficult access must still block top-pick promotion.',
  },
  {
    id: 'tinos-agios-ioannis-porto-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2149, 2151],
    reason: 'same_continuous_beachfront',
    notes: 'Agia Kyriaki and Agios Ioannis Porto are adjacent southeast-facing Porto bay records; amenities/access remain separate.',
  },
  {
    id: 'tinos-kionia-stavros-tsampia-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2165, 2178, 2188],
    reason: 'same_continuous_beachfront',
    notes: 'Kionia, Stavros, and Tsampia are neighboring south/southwest Tinos records; segment consistency does not upgrade wind confidence.',
  },
  {
    id: 'tinos-dialiskar-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2162, 2180],
    reason: 'same_continuous_beachfront',
    notes: 'Empros Dialiskar and Piso Dialiskar are adjacent southwest-facing records with similar shoreline behavior; access remains separate.',
  },
  {
    id: 'tinos-agios-romanos-apigania-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2153, 2157],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Romanos and Apigania are neighboring southwest-coast records; difficult-access status must still block top-pick promotion where relevant.',
  },
  {
    id: 'tinos-kalyvia-agios-petros-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2163, 2152],
    reason: 'same_continuous_beachfront',
    notes: 'Kalyvia and Agios Petros are nearby southwest-facing records with similar west-coast exposure behavior.',
  },
  {
    id: 'tinos-ysternia-schinaki-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2174, 2187],
    reason: 'same_village_bay',
    notes: 'Ormos Ysternion and Schinaki are adjacent Ysternia bay records and should not diverge without a specific local morphology reason.',
  },
  {
    id: 'tinos-kolympithra-north-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2166, 2173],
    reason: 'same_cove_or_micro_bay',
    notes: 'Kolympithra and Mikri Kolympithra are close north/northeast-facing records; surf/local behavior should remain separately auditable.',
  },
  {
    id: 'tinos-malli-koumelas-front',
    regionId: 'south-aegean-tinos',
    beachIds: [2171, 2167],
    reason: 'same_continuous_beachfront',
    notes: 'Malli and Koumelas are adjacent north-facing northwest Tinos records with similar open-sector behavior.',
  },
  {
    id: 'andros-gavrio-batsi-golden-front',
    regionId: 'south-aegean-andros',
    beachIds: [1688, 1726, 1705, 1686],
    reason: 'same_continuous_beachfront',
    notes: 'Agios Petros, Chrysi Ammos, Kypri, and Agios Kyprianos sit on the same practical west/southwest Gavrio-Batsi beach-front.',
  },
  {
    id: 'andros-batsi-kolona-front',
    regionId: 'south-aegean-andros',
    beachIds: [1713, 1702],
    reason: 'same_village_bay',
    notes: 'Batsi and Kolona are adjacent Batsi-bay records with similar southwest-facing behavior; popularity and amenities remain separate.',
  },
  {
    id: 'andros-vitali-gides-front',
    regionId: 'south-aegean-andros',
    beachIds: [1693, 1697],
    reason: 'same_continuous_beachfront',
    notes: 'Vitali and Gides are very close north/east Andros records with near-identical east-facing shoreline behavior.',
  },
  {
    id: 'andros-kalamitsi-kaminaki-front',
    regionId: 'south-aegean-andros',
    beachIds: [1700, 1701],
    reason: 'same_continuous_beachfront',
    notes: 'Kalamitsi and Kaminaki are adjacent northwest Andros records with similar northwest-facing exposure.',
  },
  {
    id: 'andros-megala-mikra-peza-front',
    regionId: 'south-aegean-andros',
    beachIds: [1710, 1711],
    reason: 'same_continuous_beachfront',
    notes: 'Megala Peza and Mikra Peza are adjacent northern-western records with matching northwest-facing shoreline behavior.',
  },
  {
    id: 'andros-platanistos-rozos-front',
    regionId: 'south-aegean-andros',
    beachIds: [1720, 1722],
    reason: 'same_cove_or_micro_bay',
    notes: 'Platanistos and Rozos are neighboring north-coast records; access remains separate and boat-only records must not become top picks.',
  },
  {
    id: 'andros-kourtali-felos-front',
    regionId: 'south-aegean-andros',
    beachIds: [1704, 1716],
    reason: 'same_continuous_beachfront',
    notes: 'Kourtali and Felos are close west-coast records with similar west-facing exposure behavior.',
  },
  {
    id: 'milos-provatas-agios-sostis-front',
    regionId: 'south-aegean-milos',
    beachIds: [1920, 1900],
    reason: 'same_continuous_beachfront',
    notes: 'Provatas and Agios Sostis are adjacent south-coast records with near-identical south-facing shoreline behavior.',
  },
  {
    id: 'milos-fyriplaka-tsigrado-front',
    regionId: 'south-aegean-milos',
    beachIds: [1927, 1925],
    reason: 'same_continuous_beachfront',
    notes: 'Fyriplaka and Tsigrado sit on the same south-facing cliff/beach-front; access remains separate and Tsigrado must not be promoted as mainstream.',
  },
  {
    id: 'milos-agia-kyriaki-psarovolada-front',
    regionId: 'south-aegean-milos',
    beachIds: [1901, 1931],
    reason: 'same_continuous_beachfront',
    notes: 'Agia Kyriaki and Psarovolada are adjacent south/southeast coast records with similar exposure behavior.',
  },
  {
    id: 'milos-papafragas-kapros-front',
    regionId: 'south-aegean-milos',
    beachIds: [1916, 1908],
    reason: 'same_cove_or_micro_bay',
    notes: 'Papafragas and Kapros are neighboring north-coast pocket records; keep access and danger/cove context separate from exposure consistency.',
  },
  {
    id: 'milos-kampanes-nerodafni-front',
    regionId: 'south-aegean-milos',
    beachIds: [1911, 1914],
    reason: 'same_continuous_beachfront',
    notes: 'Kampanes and Nerodafni are adjacent northwest-coast records with similar shoreline facing.',
  },
  {
    id: 'milos-rivari-fatourena-front',
    regionId: 'south-aegean-milos',
    beachIds: [1921, 1926],
    reason: 'same_continuous_beachfront',
    notes: 'Rivari and Fatourena are close west-bay/northeast-facing records; segment consistency is map-color support only, not high wind confidence.',
  },
  {
    id: 'milos-triades-ammoudaraki-front',
    regionId: 'south-aegean-milos',
    beachIds: [1924, 1902],
    reason: 'same_continuous_beachfront',
    notes: 'Triades and Ammoudaraki are neighboring difficult-access west-coast records; access difficulty remains a separate top-pick blocker.',
  },
  {
    id: 'paros-golden-beach-wind-front',
    regionId: 'south-aegean-paros',
    beachIds: [2056, 2043, 2053],
    reason: 'same_continuous_beachfront',
    notes: 'Chrysi Akti, Agkali Chrysis Aktis, and Tserdakia/Nea Chrysi Akti are the same southeast Golden Beach wind-front; wind-sport behavior can still lock stricter exposure.',
  },
  {
    id: 'paros-parikia-town-front',
    regionId: 'south-aegean-paros',
    beachIds: [2033, 2041, 2046],
    reason: 'same_village_bay',
    notes: 'Livadia, Navtikos Omilos Parou, and Paralia Parikias are adjacent Parikia town-front records and should stay consistent unless exact harbor morphology says otherwise.',
  },
  {
    id: 'paros-krios-martselo-front',
    regionId: 'south-aegean-paros',
    beachIds: [2031, 2037],
    reason: 'same_continuous_beachfront',
    notes: 'Krios and Martselo sit on the same west/northwest Parikia bay shore and should not diverge without a specific local morphology reason.',
  },
  {
    id: 'paros-santa-maria-east-front',
    regionId: 'south-aegean-paros',
    beachIds: [2038, 2051],
    reason: 'same_continuous_beachfront',
    notes: 'Mikri Santa Maria and Santa Maria are adjacent east/southeast Santa Maria coast records with similar shoreline exposure behavior.',
  },
  {
    id: 'naxos-agia-anna-prokopios-plaka-front',
    regionId: 'south-aegean-naxos',
    beachIds: [1981, 1985, 2012],
    reason: 'same_continuous_beachfront',
    notes: 'Agia Anna, Agios Prokopios, and Plaka sit on the same west resort beach-front and should not diverge without a specific geometry reason.',
  },
  {
    id: 'naxos-orkos-mikri-vigla-wind-front',
    regionId: 'south-aegean-naxos',
    beachIds: [2010, 2006],
    reason: 'same_continuous_beachfront',
    notes: 'Orkos and Mikri Vigla share the exposed west wind-front. Mikri Vigla wind-sport behavior can lock a stricter exposure, while the separate south side remains outside this segment.',
  },
  {
    id: 'naxos-alyko-kastraki-front',
    regionId: 'south-aegean-naxos',
    beachIds: [1997, 1993, 1987, 1998, 2008, 2019, 2013],
    reason: 'same_continuous_beachfront',
    notes: 'Kastraki, Glyfada, Alyko, Kedros, Mikro Alyko, Hawaii, and Pyrgaki are adjacent southwest coast pockets with similar shoreline facing; small coves remain lower confidence until separately verified.',
  },
  {
    id: 'naxos-klido-cove',
    regionId: 'south-aegean-naxos',
    beachIds: [1999, 2000],
    reason: 'same_cove_or_micro_bay',
    notes: 'Klidos and Paralia Klido are adjacent southeast/east cove records and should not diverge without a specific geometry reason.',
  },
  {
    id: 'naxos-lionas-east-bay',
    regionId: 'south-aegean-naxos',
    beachIds: [2002, 2003],
    reason: 'same_village_bay',
    notes: 'Limnari and Lionas sit on the same east/northeast bay system; nearby verified map evidence can support medium consistency, not high confidence.',
  },
  {
    id: 'naxos-southeast-coves',
    regionId: 'south-aegean-naxos',
    beachIds: [2014, 2015],
    reason: 'same_cove_or_micro_bay',
    notes: 'Rina and Spedo are neighboring southeast/south cove records with similar facing; access and exact shelter remain separately audited.',
  },
  {
    id: 'naxos-northwest-rocky-front',
    regionId: 'south-aegean-naxos',
    beachIds: [1988, 1992, 2005, 2016],
    reason: 'same_continuous_beachfront',
    notes: 'Ammitis, Glatza, Mikra, and Chilia Vrysi are north/northwest rocky-front records with similar exposure behavior.',
  },
];

const segmentByBeachId = SHORELINE_SEGMENTS.reduce<Map<number, ShorelineSegment>>((lookup, segment) => {
  segment.beachIds.forEach(beachId => {
    lookup.set(beachId, segment);
  });
  return lookup;
}, new Map());

export const getShorelineSegment = (beachId: number): ShorelineSegment | undefined => (
  segmentByBeachId.get(beachId)
);

export const getShorelineSegmentId = (beachId: number): string | undefined => (
  getShorelineSegment(beachId)?.id
);

export const areInSameShorelineSegment = (aBeachId: number, bBeachId: number): boolean => {
  const aSegmentId = getShorelineSegmentId(aBeachId);
  return Boolean(aSegmentId && aSegmentId === getShorelineSegmentId(bBeachId));
};
