import { Beach, WindProfile } from '../types';

type OverrideEntry = {
  islandTokens: string[];
  nameTokens: string[];
  profile: WindProfile;
};

const normalizeToken = (value: string | undefined): string => (
  (value || '')
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLocaleLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
);

const unverifiedWindProfile = (notes: string): WindProfile => ({
  beachFacingDirection: null,
  shelterLevel: 'unknown',
  fetchExposure: 'unknown',
  exposedToWindDirections: [],
  protectedFromWindDirections: [],
  knownWindSportSpot: false,
  localWindAmplification: 'unknown',
  confidence: 'low',
  notes,
});

const lowConfidenceDirectionalProfile = ({
  beachFacingDirection,
  shelterLevel,
  fetchExposure,
  exposedToWindDirections,
  knownWindSportSpot = false,
  localWindAmplification = 'low',
  suspectPin = false,
  notes,
}: Pick<WindProfile, 'beachFacingDirection' | 'shelterLevel' | 'fetchExposure' | 'exposedToWindDirections' | 'notes'> & {
  knownWindSportSpot?: WindProfile['knownWindSportSpot'];
  localWindAmplification?: WindProfile['localWindAmplification'];
  suspectPin?: WindProfile['suspectPin'];
}): WindProfile => ({
  beachFacingDirection,
  shelterLevel,
  fetchExposure,
  exposedToWindDirections,
  protectedFromWindDirections: [],
  knownWindSportSpot,
  localWindAmplification,
  confidence: 'low',
  suspectPin,
  notes,
});

const lowConfidenceMilosProfile = lowConfidenceDirectionalProfile;

export const windProfileOverridesByBeachId: Record<number, WindProfile> = {
  1727: unverifiedWindProfile(
    'Milos west/southwest remote beach. Exact cove orientation and fetch need local verification; avoid protected/calm claims.'
  ),
  1728: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South-coast Milos beach near the Provatas zone. Likely more manageable than open north-coast beaches in north wind, but not verified enough for calm/protected claims.',
  },
  1729: {
    beachFacingDirection: 165,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'E'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South/southeast Milos beach. Often a better north-wind candidate than north-coast beaches, while east/south-sector wind can still affect comfort.',
  },
  1730: unverifiedWindProfile(
    'Milos west-side remote beach. Small-cove shelter and west/southwest swell sensitivity need local verification.'
  ),
  1731: {
    beachFacingDirection: 0,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'high',
    notes: 'High-confidence wind-sport exposure evidence 2026-06-08: Let’s Kite identifies Milos/Axivadolimni at 36.69, 24.45 for kitesurf/wingfoil/windsurf, facing north with direct onshore Meltemi and summer 15-22 kt conditions. Treat as a wind/watersports caution, not as a calm-swimming recommendation in 4-5 Bft north wind.',
  },
  1732: unverifiedWindProfile(
    'Remote southwest Milos cove. Cliff shelter may exist, but access and local sea-state behavior need verification before any wind-protection claim.'
  ),
  1733: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'North-side Milos exposure inferred from coordinates. Treat as meltemi-sensitive and avoid calm/protected wording until verified locally.',
  },
  1734: lowConfidenceMilosProfile({
    beachFacingDirection: 90,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'high',
    exposedToWindDirections: ['SE'],
    notes: 'Eastern Milos beach near the old sulfur mine area. 2026-06-10 golden-island pass: high-res OSM geometry shows ~25 km of open SE fetch toward the Milos-Kimolos-Polyaigos gap, so SE wind is treated as exposed; other sectors and access/sea-state risks still need verification.',
  }),
  1736: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'Small north-side Milos beach near Papafragas. Treat as meltemi-sensitive and do not infer calm/protected behavior without local verification.',
  },
  1737: unverifiedWindProfile(
    'Remote southwest/south Milos beach. Do not infer safe shelter from broad south-coast position; access and fetch need local verification.'
  ),
  1738: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'low',
    notes: 'South-coast Milos beach inferred as a possible north-wind alternative, but exact local shelter is not verified.',
  },
  1740: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'low',
    notes: 'Adamas bay/harbor area with likely lower open-sea fetch. Keep as a practical bay hypothesis, not a premium calm-swimming claim.',
  },
  1741: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'low',
    notes: 'Adamas bay/harbor-side beach. Possible low-fetch option, but local swimming value and wind behavior need verification.',
  },
  1742: {
    beachFacingDirection: 0,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    suspectPin: true,
    notes: 'Northern Milos exposure inferred from coordinates. 2026-06-10 golden-island pass: high-res OSM geometry at the pin shows a west-opening shoreline with ~19 km west fetch (sunset-spot guide references agree), while this legacy profile is north-facing; the coastal corner here (Kampanes 200 m NE) makes the true facing ambiguous. Conservative union of both exposures kept; facing needs field verification.',
  },
  1743: {
    beachFacingDirection: 155,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'E'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South/east Milos beach. Likely a better candidate in north wind than open north-coast beaches, but south/east winds are the local caution.',
  },
  1744: {
    beachFacingDirection: 15,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: ['S', 'SE', 'SW'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North-coast cave/cove beach. Pocket shelter is possible, but north-sector waves or surge can enter; never treat as simply calm/protected in meltemi.',
  },
  1745: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'low',
    notes: 'Papikinou local-exception candidate inside the Adamas bay area. Align with adjacent Nautical Club bay-front behavior: south-sector wind can be onshore inside the bay, while north-sector wind is generally lower-fetch. This remains low confidence and must not imply guaranteed calm water.',
  },
  1747: {
    beachFacingDirection: 340,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: ['S', 'SE', 'SW'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest/north Milos beach. Meltemi can be a direct comfort issue; south/southwest wind is usually less onshore here, but this is not a guaranteed calm-water claim.',
  },
  1748: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Main south-coast Milos option. Often more practical in north wind than exposed northern beaches, but south-sector wind can reverse the recommendation.',
  },
  1749: {
    beachFacingDirection: 30,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['N', 'NE'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Milos golden-island evidence pass 2026-06-10: Rivari sits on the west shore of the Milos gulf by the Rivari lagoon, between Emporios and Fatourena (Greeka + feelgreece location evidence; high-res OSM geometry faces ~30deg into the gulf). The old west-facing/W-SW-exposed profile described the open outer coast, not this gulf-side beach. Cross-gulf N/NE chop is the remaining caution; no calm/protected claim.',
  },
  1750: {
    beachFacingDirection: 0,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: ['S', 'SE', 'SW'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Sarakiniko is a high-impact north-coast sightseeing beach. Do not treat it as calm/protected in meltemi; south/southwest wind is usually less onshore here, but recommend only when sea and wind data support swimming.',
  },
  1751: {
    beachFacingDirection: 340,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: ['S', 'SE', 'SW'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North/northwest Milos beach. Treat as meltemi-sensitive and avoid calm-family recommendations in 4-5 Bft north-sector wind; south/southwest wind is generally less onshore here.',
  },
  1752: unverifiedWindProfile(
    'West-coast Milos coves. Local pockets may exist, but orientation, swell exposure, and remote access need verification.'
  ),
  1753: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South-coast cove that may be better in north wind. Access is difficult and wind shelter must not be interpreted as safe swimming in poor sea conditions.',
  },
  1754: {
    beachFacingDirection: 5,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['N', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Milos golden-island evidence pass 2026-06-10: Fatourena is on the south shore of the Milos gulf next to the Rivari lagoon and Emporios (named as the nearby swimming beach by embourios.com; high-res OSM geometry faces ~5deg into the gulf with up to ~8 km cross-gulf fetch). North-sector wind builds real chop here, so N/NW stay exposed; the old SW/W-exposed outer-coast profile was a location error.',
  },
  1755: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Popular south-coast Milos beach. Likely a better north-wind option than open northern beaches, but do not oversell it in south/east wind.',
  },
  1757: {
    beachFacingDirection: 340,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    // 2026-06-10 golden-island pass: high-res geometry shows ~12 km of open
    // fetch through the inlet mouth toward the NE (Milos-Kimolos strait), so
    // NE joins the exposed sectors.
    exposedToWindDirections: ['N', 'NW', 'NE'],
    protectedFromWindDirections: ['S', 'SE', 'SW'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North-coast village bay. Beautiful and practical in some conditions, but should not be sold as calm/protected during meltemi; southwest wind is generally less direct than north-sector wind.',
  },
  1758: unverifiedWindProfile(
    'Remote south/southwest Milos beach. Broad geography suggests it can differ from north beaches, but exposure and access need verification.'
  ),
  1759: {
    beachFacingDirection: 160,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE', 'E'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southeast Milos beach near the Agia Kyriaki/Palaiochori zone. Likely better in north wind, but east/south-sector wind remains a caution.',
  },
  1817: {
    beachFacingDirection: 225,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['SW', 'W'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southwest Paros cove. Likely better in north-sector wind than open east/north beaches, but not a universal calm guarantee.',
  },
  1822: {
    beachFacingDirection: 225,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['SW', 'W'],
    protectedFromWindDirections: ['N', 'NE'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southwest Paros beach; should behave better than north/east exposed beaches in north wind, but bay shelter needs local check.',
  },
  1827: {
    beachFacingDirection: 315,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['NE', 'E'],
    protectedFromWindDirections: ['N', 'NW', 'W'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'high',
    notes: 'High-confidence sheltered-bay evidence 2026-06-08: Paros municipal tourism identifies Kolympithres inside Naoussa bay as a windless/calm bay with calm, warm, shallow water. Keep NE/E as local caution sectors; do not generalize to all wind directions.',
  },
  1833: {
    beachFacingDirection: 180,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South-facing Paros beach; likely a better north-wind swimming option than open east/north beaches. South-sector winds are the caution.',
  },
  1835: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northeast Paros beach with open fetch; north-sector wind can feel breezy/choppy. Do not sell as protected in meltemi.',
  },
  1836: {
    beachFacingDirection: 315,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['NE', 'E'],
    protectedFromWindDirections: ['N', 'NW', 'W'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'high',
    notes: 'High-confidence sheltered-cove evidence 2026-06-08: Paros guide describes Monastiri in the Ai-Giannis Detis/Paros Park cove as shallow, calm, and protected even from strong winds by surrounding hills. Keep NE/E as local caution sectors.',
  },
  1837: {
    beachFacingDirection: 75,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Open east-side bay facing toward Naxos. North/east-sector wind can build chop quickly; not a calm protected pick in meltemi.',
  },
  1840: {
    beachFacingDirection: 105,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'medium',
    notes: 'Part of the Golden Beach wind/watersports cluster. Treat like high-exposure in 4-5 Bft; separate from calmer south-coast alternatives.',
  },
  1841: {
    beachFacingDirection: 210,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'high',
    notes: 'High-confidence sheltered-village-bay evidence 2026-06-08: Paros municipal tourism describes Aliki as a fishing village that developed because of natural shelter from winds, with nearby calm south-coast bays. Keep S/SW as local exposure caution.',
  },
  1842: {
    beachFacingDirection: 180,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South Paros beach with some north-wind lee effect. Keep as semi-sheltered because exact cove protection needs local verification.',
  },
  1848: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northeast Paros beach with open Aegean fetch. North-sector wind can be uncomfortable for relaxed swimming.',
  },
  1850: {
    beachFacingDirection: 100,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'high',
    notes: 'High-confidence wind-sport exposure evidence 2026-06-08: Paros Windsurf Center is located at New Golden Beach/Tserdakia and describes it as a reliable Meltemi windsurf/wingfoil spot facing the summer northerly wind. Do not treat as calm/protected in 4-5 Bft.',
  },
  1851: {
    beachFacingDirection: 60,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'high',
    notes: 'High-confidence wind-sport exposure evidence 2026-06-08: Let’s Kite identifies Tsoukalia/Paros at 37.08, 25.26 for kitesurf/wingfoil/windsurf, with N/NNE Meltemi onshore to side-onshore, reliable summer wind, and moderate chop. Avoid calm-family claims in meltemi.',
  },
  1852: {
    beachFacingDirection: 195,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: ['S', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'NW'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'high',
    notes: 'High-confidence sheltered-cove evidence 2026-06-08: Paros guide says Farangas is in a small southern bay, protected from wind and not affected by northern winds; Paros municipal tourism also describes the Faragas coves as sheltered by cliffs with calm clear water. Keep S/SW as local exposure caution.',
  },
  1853: {
    beachFacingDirection: 100,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'high',
    notes: 'Known wind/windsurf beach, also called Golden Beach. Exposed enough that 4-5 Bft should not be sold as calm/protected.',
  },
  1818: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North/northeast Paros beach with likely open fetch. North-sector wind can feel windy/choppy; avoid calm/protected claims in meltemi.',
  },
  1819: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North Paros beach with likely N/NE exposure. Treat as wind-sensitive in 4-5 Bft unless local conditions prove otherwise.',
  },
  1820: {
    beachFacingDirection: 70,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northeast/east Paros beach with Aegean fetch. North/east-sector wind can create chop; do not promote as protected in meltemi.',
  },
  1821: {
    beachFacingDirection: 75,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'East/northeast Paros exposure inferred from position. Use as wind-sensitive and avoid calm/protected wording in strong northerlies.',
  },
  1823: {
    beachFacingDirection: 75,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'East Paros open-fetch beach. North/east-sector wind can build chop quickly, so keep it out of calm-family claims in meltemi.',
  },
  1824: {
    beachFacingDirection: 260,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'SW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'West Paros bay-side beach. Some local shelter may help, but protection is not verified enough for protected/calm claims.',
  },
  1825: {
    beachFacingDirection: 120,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['E', 'SE', 'S'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southeast Paros beach with directional exposure. It may behave differently from north-facing beaches, but exact shelter needs local check.',
  },
  1826: {
    beachFacingDirection: 80,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'East Paros beach with open fetch toward the Aegean. NE/E wind can affect comfort; avoid protected/calm claims.',
  },
  1828: {
    beachFacingDirection: 275,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Parikia bay area beach. Keep as semi-sheltered because bay shelter is not enough to make a verified north-wind protection claim.',
  },
  1829: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North/northeast Paros beach with likely open exposure. Strong north-sector wind can be uncomfortable for casual swimming.',
  },
  1830: {
    beachFacingDirection: 275,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Parikia bay beach. Treat as partly sheltered only; do not create protected-from-north or calm-water claims from this profile.',
  },
  1831: unverifiedWindProfile(
    'Wind exposure not verified for this Paros beach. Keep conservative scoring and avoid protected/calm claims until orientation and fetch are checked.'
  ),
  1832: {
    beachFacingDirection: 120,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['E', 'SE', 'S'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southeast Paros beach. It can differ from north-exposed beaches, but exact local shelter is not verified enough for protected claims.',
  },
  1834: {
    beachFacingDirection: 270,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Parikia bay beach with partial bay influence. Keep as semi-sheltered and avoid north-wind protection claims without local verification.',
  },
  1838: {
    beachFacingDirection: 275,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Parikia waterfront/bay area. Urban bay position may reduce fetch, but not enough for a verified protected/calm label.',
  },
  1839: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northeast Paros beach with likely Aegean exposure. North/east-sector wind can make it choppy; avoid calm/protected claims.',
  },
  1843: {
    beachFacingDirection: 260,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Parikia bay beach. Use as semi-sheltered only; the profile must not imply verified protection from north wind.',
  },
  1844: {
    beachFacingDirection: 225,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['SW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southwest Paros beach that may be more practical than open north/east beaches, but local protection still needs verification.',
  },
  1845: {
    beachFacingDirection: 315,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['N', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Naousa bay area beach. Keep as semi-sheltered because exact cove shelter is not verified for north-wind calm claims.',
  },
  1846: {
    beachFacingDirection: 270,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'W', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: true,
    localWindAmplification: 'high',
    confidence: 'medium',
    suspectPin: true,
    notes: 'Known windy/kite area; should not be promoted as calm with 4-5 Beaufort. 2026-06-11 name-collision flag: this profile describes the WEST-coast kite Pounta (Antiparos strait), but the app pin (37.028, 25.252) sits at the EAST-coast Punda beach-club area next to Tserdakia. Correct fix is either moving the pin to the west-coast Pounta or a separate record for Punda Beach Club - pending Miltos decision; until then geometry from this pin must not override the authored facing.',
  },
  1847: {
    beachFacingDirection: 190,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South Paros beach. It may perform differently from north-exposed beaches, but use cautious wording until local shelter is verified.',
  },
  1849: {
    beachFacingDirection: 0,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North Paros beach with direct north-sector exposure. Strong northerlies can be uncomfortable; do not label as protected.',
  },
  1503: {
    beachFacingDirection: 270,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: ['NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'West Andros practical beach near Gavrio/Batsi. Better than open east bays in NE wind, but not verified as protected from due north.',
  },
  1505: {
    beachFacingDirection: 270,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: ['NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Open west-coast sandy beach. Often more practical than east-coast bays in NE wind, but can still feel breezy/choppy with N/NW.',
  },
  1541: {
    beachFacingDirection: 90,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Open east-side bay; north-sector wind can build chop/waves quickly. Do not claim protected in meltemi.',
  },
  1535: {
    beachFacingDirection: 180,
    shelterLevel: 'sheltered',
    fetchExposure: 'low',
    exposedToWindDirections: [],
    protectedFromWindDirections: ['N', 'NW', 'W'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'More sheltered Andros option; usually better than open north/east bays during north-sector wind. Not a universal calm guarantee.',
  },
  1506: {
    beachFacingDirection: 200,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SW'],
    protectedFromWindDirections: ['N', 'NE'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South-coast beach; should behave differently from north-exposed beaches in north wind, but remains exposed with S/SW wind.',
  },
  1508: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'East/northeast Andros beach. North-sector wind can create uncomfortable chop quickly; avoid protected/calm claims.',
  },
  1509: {
    beachFacingDirection: 75,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Open east-coast Andros beach with long Aegean fetch. Strong north/east-sector winds can make swimming less comfortable.',
  },
  1510: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'North/east-facing Andros beach. Meltemi can arrive directly and build chop; not a calm-family fallback in 4-5 Bft.',
  },
  1512: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Open north/east Andros beach. High fetch in north-sector wind; use caution for casual swimming during meltemi.',
  },
  1516: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Large northern Andros beach with open fetch. North wind can be a direct comfort problem; avoid calm/protected wording.',
  },
  1519: {
    beachFacingDirection: 260,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: ['NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    suspectPin: true,
    notes: 'Small Batsi-area beach. Practical leeward alternative in some east/northeast winds, but not confirmed protected from due north. 2026-06-10 flag: the app pin sits in a 60 m water pocket east of the beach ridge while the Batsi coast opens SW - geometry from this pin is not trusted.',
  },
  1522: {
    beachFacingDirection: 270,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: ['NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'West-coast practical beach. Often preferable to open east/north bays in NE wind, but N/NW wind can still be felt.',
  },
  1530: {
    beachFacingDirection: 260,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'SW'],
    protectedFromWindDirections: ['N', 'NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Batsi bay area; more practical in north/east-sector wind than exposed east beaches, though not guaranteed flat everywhere in the bay.',
  },
  1543: {
    beachFacingDirection: 270,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['W', 'NW'],
    protectedFromWindDirections: ['NE', 'E'],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Popular west-coast Andros beach. Better than east open bays in NE wind, but still not a verified sheltered cove for due north wind.',
  },
  1504: {
    beachFacingDirection: 155,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South/east Andros beach with possible lee from north-sector wind, but protection is not verified enough for protected/calm claims.',
  },
  1507: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'Remote/northern Andros exposure inferred from position. Treat as wind-sensitive, but keep confidence low until shoreline is verified.',
  },
  1511: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros open-fetch beach. North/west-sector wind can build chop quickly; avoid calm/protected wording.',
  },
  1513: {
    beachFacingDirection: 170,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South Andros/Korthi-side beach. It may differ from north-exposed beaches, but exact shelter is not verified enough for protected claims.',
  },
  1514: {
    beachFacingDirection: 45,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'Northern Andros exposure inferred from broad geography. Treat as open/high-fetch in northerlies, with low confidence pending review.',
  },
  1515: {
    beachFacingDirection: 70,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Chora/east-side Andros beach with likely north/east exposure. Do not promote as calm/protected in meltemi.',
  },
  1517: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros beach with open fetch. North/west-sector winds can make casual swimming uncomfortable.',
  },
  1518: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros beach near other exposed coves. Treat as wind-sensitive in 4-5 Bft northerlies.',
  },
  1520: unverifiedWindProfile(
    'Wind exposure not verified for this Andros beach. Use conservative scoring and avoid sheltered/calm claims until orientation and fetch are confirmed.'
  ),
  1521: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest/west Andros open-fetch beach. Strong north/west-sector winds can be uncomfortable for relaxed swimming.',
  },
  1523: unverifiedWindProfile(
    'Local wind exposure needs verification. Do not treat this Andros beach as protected until beach orientation and fetch are checked.'
  ),
  1524: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'Northern Andros natural coast with likely open fetch. Keep low confidence and avoid any sheltered/calm wording.',
  },
  1525: unverifiedWindProfile(
    'Small-cove/harbor shelter is not verified. Keep this profile unknown and avoid protected/calm claims until local geometry is checked.'
  ),
  1526: {
    beachFacingDirection: 145,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['E', 'SE', 'S'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Southeast/east Andros beach. May differ from north-exposed beaches, but exact shelter is not verified enough for protected claims.',
  },
  1527: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'North Andros beach with likely open fetch. Treat as exposed in northerlies, but keep low confidence until shoreline is verified.',
  },
  1528: {
    beachFacingDirection: 15,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'NW'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'low',
    notes: 'North Andros small beach with likely open exposure. Use conservative exposed scoring and avoid calm/protected claims.',
  },
  1529: unverifiedWindProfile(
    'Wind exposure pattern is not verified. Keep low confidence and avoid protected/calm claims until local orientation and fetch are checked.'
  ),
  1531: {
    beachFacingDirection: 160,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'South Andros beach. It may be more practical than open north/east beaches in north wind, but not verified as fully sheltered.',
  },
  1532: {
    beachFacingDirection: 240,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['SW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'West/southwest Andros beach. Often behaves differently from open east beaches, but do not use this as a north-protection claim.',
  },
  1533: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros beach with open-sector exposure. North/west winds can make it choppy; avoid protected/calm wording.',
  },
  1534: {
    beachFacingDirection: 75,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NE', 'E'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Chora-side Andros beach with likely wind exposure. Treat as wind-sensitive and do not claim north-wind protection.',
  },
  1536: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros cove with open-fetch risk. North/west-sector wind can be uncomfortable for casual swimming.',
  },
  1537: unverifiedWindProfile(
    'Exposure pattern is unclear from available metadata. Keep as unknown/low confidence and avoid protected/calm claims.'
  ),
  1538: {
    beachFacingDirection: 315,
    shelterLevel: 'open',
    fetchExposure: 'high',
    exposedToWindDirections: ['N', 'NW', 'W'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'medium',
    confidence: 'medium',
    notes: 'Northwest Andros beach with likely open fetch. Strong north/west-sector wind should be treated as a swimming comfort risk.',
  },
  1539: unverifiedWindProfile(
    'Local wind exposure is not verified. Keep low confidence and avoid any protected/calm label until orientation and fetch are checked.'
  ),
  1540: unverifiedWindProfile(
    'Wind exposure not verified for this Andros beach. Use unknown shelter/fetch and avoid sheltered/calm claims until reviewed.'
  ),
  1542: {
    beachFacingDirection: 155,
    shelterLevel: 'semi_sheltered',
    fetchExposure: 'medium',
    exposedToWindDirections: ['S', 'SE'],
    protectedFromWindDirections: [],
    knownWindSportSpot: false,
    localWindAmplification: 'low',
    confidence: 'medium',
    notes: 'Korthi/southeast Andros beach. It may differ from north-exposed beaches, but gusts and local exposure still need caution.',
  },
};

const legacyMilosOverrideEntries: OverrideEntry[] = [
  { islandTokens: ['milos'], nameTokens: ['Agios Ioannis'], profile: windProfileOverridesByBeachId[1727] },
  { islandTokens: ['milos'], nameTokens: ['Agios Sostis'], profile: windProfileOverridesByBeachId[1728] },
  { islandTokens: ['milos'], nameTokens: ['Agia Kyriaki'], profile: windProfileOverridesByBeachId[1729] },
  { islandTokens: ['milos'], nameTokens: ['Ammoudaraki'], profile: windProfileOverridesByBeachId[1730] },
  { islandTokens: ['milos'], nameTokens: ['Achivadolimni'], profile: windProfileOverridesByBeachId[1731] },
  { islandTokens: ['milos'], nameTokens: ['Gerontas'], profile: windProfileOverridesByBeachId[1732] },
  { islandTokens: ['milos'], nameTokens: ['Gerania'], profile: windProfileOverridesByBeachId[1733] },
  { islandTokens: ['milos'], nameTokens: ['Theiafes', 'Thiafes'], profile: windProfileOverridesByBeachId[1734] },
  { islandTokens: ['milos'], nameTokens: ['Kapros'], profile: windProfileOverridesByBeachId[1736] },
  { islandTokens: ['milos'], nameTokens: ['Katergo'], profile: windProfileOverridesByBeachId[1737] },
  { islandTokens: ['milos'], nameTokens: ['Kipoi', 'Kipi'], profile: windProfileOverridesByBeachId[1738] },
  { islandTokens: ['milos'], nameTokens: ['Lagkada'], profile: windProfileOverridesByBeachId[1740] },
  { islandTokens: ['milos'], nameTokens: ['Navtikos Omilos Milou'], profile: windProfileOverridesByBeachId[1741] },
  { islandTokens: ['milos'], nameTokens: ['Nerodafni'], profile: windProfileOverridesByBeachId[1742] },
  { islandTokens: ['milos'], nameTokens: ['Palaiochori'], profile: windProfileOverridesByBeachId[1743] },
  { islandTokens: ['milos'], nameTokens: ['Papafragkas'], profile: windProfileOverridesByBeachId[1744] },
  { islandTokens: ['milos'], nameTokens: ['Papikinoy', 'Papikinou'], profile: windProfileOverridesByBeachId[1745] },
  { islandTokens: ['milos'], nameTokens: ['Plathiena'], profile: windProfileOverridesByBeachId[1747] },
  { islandTokens: ['milos'], nameTokens: ['Provatas'], profile: windProfileOverridesByBeachId[1748] },
  { islandTokens: ['milos'], nameTokens: ['Rivari'], profile: windProfileOverridesByBeachId[1749] },
  { islandTokens: ['milos'], nameTokens: ['Sarakiniko'], profile: windProfileOverridesByBeachId[1750] },
  { islandTokens: ['milos'], nameTokens: ['Tourkothalassa'], profile: windProfileOverridesByBeachId[1751] },
  { islandTokens: ['milos'], nameTokens: ['Triades'], profile: windProfileOverridesByBeachId[1752] },
  { islandTokens: ['milos'], nameTokens: ['Tsigkrado'], profile: windProfileOverridesByBeachId[1753] },
  { islandTokens: ['milos'], nameTokens: ['Fatoyrena', 'Fatourena'], profile: windProfileOverridesByBeachId[1754] },
  { islandTokens: ['milos'], nameTokens: ['Fyriplaka'], profile: windProfileOverridesByBeachId[1755] },
  { islandTokens: ['milos'], nameTokens: ['Fyropotamos'], profile: windProfileOverridesByBeachId[1757] },
  { islandTokens: ['milos'], nameTokens: ['Psathi'], profile: windProfileOverridesByBeachId[1758] },
  { islandTokens: ['milos'], nameTokens: ['Psarovolada'], profile: windProfileOverridesByBeachId[1759] },
];

const milosPhase3CoverageOverrideEntries: OverrideEntry[] = [
  {
    islandTokens: ['milos'],
    nameTokens: ['Agios Dimitrios'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 300,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      suspectPin: true,
      notes: 'Northwest/west Milos beach inferred from current coordinates and legacy orientation fallback. Treat as meltemi/west-sector sensitive until local behavior is verified; no protected/calm claims. 2026-06-10 golden-island pass: the app pin sits INSIDE the Milos gulf while curated data + guides (boat-only cove on the west edge, Greeka/feelgreece/MarinaTips) describe the real beach elsewhere — geometry from the current pin is not trusted; pin location needs field verification.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Kalamos'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 175,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SE', 'SW', 'E'],
      notes: 'South-coast Milos beach. 2026-06-10 golden-island pass: high-res OSM geometry adds ~15 km of open east fetch toward the Milos-Kimolos-Polyaigos gap, so E joins the exposed sectors; exact local shelter still needs verification.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Kampanes'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 330,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W', 'NE'],
      localWindAmplification: 'medium',
      suspectPin: true,
      notes: 'Northern Milos location inferred from current coordinates. 2026-06-10 golden-island pass: high-res OSM geometry adds ~17 km of open NE fetch toward the strait mouth; coastal-corner ambiguity with adjacent Nerodafni (200 m SW) — conservative union of exposures kept, facing needs field verification.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Paralia Aggathia', 'Paralia Angathia'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 285,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['W', 'NW', 'SW'],
      localWindAmplification: 'medium',
      notes: 'West-side Milos beach inferred from current coordinates. West and northwest-sector exposure need caution; profile remains low confidence.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Fyrlingkos'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 135,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      notes: 'East/southeast Milos beach inferred from current coordinates. It may be less exposed than north beaches in north wind, but east/south-sector wind remains a caution.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Pollonia'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 45,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'Northeast Milos village/beach area. Geography suggests north/east-sector sensitivity, but local bay behavior needs verification before stronger claims.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Agkali'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 90,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['NE', 'E', 'SE'],
      notes: 'East-side Milos beach near the Pollonia/Voudia side. Treat east-sector wind as the main caution; no verified shelter claim.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Voydia', 'Voudia'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 70,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'Northeast/east Milos rocky-pebble beach inferred from coordinates and terrain. Treat as exposed in north/east-sector wind until locally verified. 2026-06-10 evidence pass: guides (Greeka, meraviglioseisolegreche) warn of strong sea currents off Voudia, and high-res geometry shows Kimolos shading the due-north fetch — kept the conservative explicit N exposure pending field verification of channel funneling.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Kastanas'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 80,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East-side Milos rocky-pebble beach with passable dirt-road access. North/east-sector exposure is a low-confidence geospatial inference.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Kolympisionas'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 85,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['NE', 'E', 'SE'],
      localWindAmplification: 'medium',
      notes: 'East-side Milos rocky-pebble beach reached by path. Treat east-sector wind as exposed; keep low confidence and avoid calm/protected claims.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Rema'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 120,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      notes: 'Southeast/east Milos small beach inferred from current coordinates. South/east-sector wind is the main caution; local behavior still needs verification.',
    }),
  },
  {
    islandTokens: ['milos'],
    nameTokens: ['Tria Pigadia'],
    profile: lowConfidenceMilosProfile({
      beachFacingDirection: 75,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East/northeast Milos beach inferred from current coordinates. Treat north/east-sector wind as exposed until verified locally.',
    }),
  },
];

const lowConfidenceNaxosProfile = lowConfidenceDirectionalProfile;
const mediumConfidenceNaxosProfile = (
  input: Parameters<typeof lowConfidenceDirectionalProfile>[0]
): WindProfile => ({
  ...lowConfidenceDirectionalProfile(input),
  confidence: 'medium',
  notes: `${input.notes} Naxos wind-profile evidence gate 2026-06-08: verified OSM or verified nearby Nominatim identity, medium geospatial exposure, and no authored/geospatial sector conflict support medium confidence. This does not create a verified calm/protected claim.`,
});

const naxosPhase1CoverageOverrideEntries: OverrideEntry[] = [
  {
    islandTokens: ['naxos'],
    nameTokens: ['Agia Anna'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 260,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'West-coast Naxos beach inferred from current coordinates and official beach metadata. Treat west-sector wind as the main caution; no verified protected/calm claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Agiassos'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 205,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SW', 'W'],
      notes: 'Southwest/south Naxos beach inferred from coordinates. North-wind behavior may be better than open north/east beaches, but shelter is not locally verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Agioi Theodoroi', 'Agii Theodori'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 20,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'NW'],
      localWindAmplification: 'medium',
      notes: 'North Naxos beach inferred from coordinates. Treat north-sector wind as exposed until local wave behavior is verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Agios Georgios'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 245,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'West/town-side Naxos beach with shallow organized sections. Orientation is inferred from coordinates; avoid protected/calm wording until locally verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Agios Prokopios'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 265,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'West-coast Naxos beach inferred from coordinates and source metadata. West/northwest-sector wind remains the main caution.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Azalas'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 85,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East-side Naxos pebble/rock beach inferred from coordinates. Treat north/east-sector wind as exposed; local shelter still needs verification.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Alyko'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 250,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Southwest/west Naxos beach inferred from coordinates near the Alyko area. No verified calm/protected claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Ammitis'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 330,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'Northwest/north Naxos beach inferred from coordinates. Treat north/west-sector wind as exposed until reviewed locally.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Ampram'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 35,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'North/northeast Naxos beach inferred from coordinates. North/east-sector wind should be treated with caution.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Apollonas'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 45,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'Northeast Naxos village beach inferred from coordinates. Bay behavior needs local validation, so no protected/calm claim is made.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Vintzi'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 290,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'NW', 'N'],
      notes: 'Town/west-side Naxos pebble beach inferred from coordinates. Keep low confidence until exact cove exposure is verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Glatza'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 330,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'Northwest/north Naxos rocky-pebble beach inferred from coordinates. Treat north/west-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Glyfada'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 250,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Southwest/west Naxos sandy beach inferred from coordinates. West-sector wind is the main caution; no verified protection claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Grotta'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 315,
      shelterLevel: 'open',
      fetchExposure: 'medium',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'Naxos town/northwest beach inferred from coordinates. Treat north/west-sector wind as a caution and avoid calm wording.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Kalantos'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 180,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SE', 'SW'],
      notes: 'South Naxos beach inferred from coordinates. It may differ from north-exposed beaches in meltemi, but exact bay shelter is unverified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Kampos'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 25,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'NW'],
      localWindAmplification: 'medium',
      notes: 'North Naxos beach inferred from coordinates. North-sector wind should be treated as exposed until local behavior is reviewed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Kastraki'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 245,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Southwest/west Naxos sandy beach inferred from coordinates. No verified calm/protected claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Kedros'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 250,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Southwest/west Naxos beach near Alyko inferred from coordinates. Keep low confidence until exact cove shelter is verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Kleidos', 'Klidos'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 120,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['E', 'SE', 'S'],
      localWindAmplification: 'medium',
      notes: 'Southeast/east Naxos beach inferred from coordinates. Treat east/south-sector wind as exposed; no protected/calm claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Kleido', 'Paralia Klido'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 120,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['E', 'SE', 'S'],
      localWindAmplification: 'medium',
      notes: 'Southeast/east Naxos beach inferred from coordinates. East/south-sector wind remains the main caution.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Ligaridia'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 85,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East-side Naxos pebble beach inferred from coordinates. Treat north/east-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Limnari'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 80,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East/northeast Naxos beach inferred from coordinates. North/east-sector wind should be handled as exposed until verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Lionas'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 80,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East/northeast Naxos village beach inferred from coordinates. Treat north/east-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Melino'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 15,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'NW'],
      localWindAmplification: 'medium',
      notes: 'North Naxos beach inferred from coordinates. Treat north-sector wind as exposed; no verified shelter claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Mikra'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 345,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'North/northwest Naxos beach inferred from coordinates. Treat north/west-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Mikri Vigla'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 300,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'West/southwest Naxos beach with source metadata showing organized watersports. Treat north/west-sector wind as a wind/watersports caution, not as a calm-swimming pick.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Mikri Vigla - Notia plevra'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 205,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SW', 'W'],
      notes: 'South side of the Mikri Vigla area inferred from coordinates. Exact wind separation from the north side needs local verification.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Mikro Alyko'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 250,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Small southwest/west Naxos cove inferred from coordinates. Keep low confidence; no verified calm/protected claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Moutsoyna', 'Moutsouna'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 90,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['NE', 'E', 'SE'],
      localWindAmplification: 'medium',
      notes: 'East-side Naxos village beach inferred from coordinates. Bay behavior may vary, so east-sector wind is a caution without protection claims.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Orkos'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 285,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'West/southwest Naxos beach near the Mikri Vigla strip inferred from coordinates. Treat north/west-sector wind as exposed until locally verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Panormos'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 145,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      suspectPin: true,
      notes: 'Southeast/south Naxos beach inferred from coordinates. South/east-sector wind remains a caution; local bay shelter needs verification. 2026-06-10 flag: the app pin sits in a SW-opening notch/harbour pocket in the high-res mask while the real bay opens SE - geometry from this pin is not trusted.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Plaka'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 260,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Long west-coast Naxos beach inferred from coordinates. West/northwest-sector wind is the main caution; no verified protected/calm claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Pyrgaki'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 230,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SW', 'W'],
      notes: 'Southwest Naxos sandy beach inferred from coordinates. Treat south/west-sector wind as exposed until locally verified.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Rina'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 155,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      notes: 'Boat-access southeast/south Naxos cove inferred from coordinates. Access and exact shelter need local verification; no calm/protected claim.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Spedo'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 145,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      notes: 'Southeast/south Naxos beach inferred from coordinates. Treat east/south-sector wind as the main caution.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Chilia Vrysi'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 350,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      localWindAmplification: 'medium',
      notes: 'North Naxos pebble/rock beach inferred from coordinates. Treat north/west-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Psili Ammos'],
    profile: mediumConfidenceNaxosProfile({
      beachFacingDirection: 110,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['E', 'SE', 'S'],
      notes: 'East/southeast Naxos sandy beach inferred from coordinates and source metadata. East/south-sector wind remains a caution.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Paralia Psofagrilia'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 85,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      localWindAmplification: 'medium',
      notes: 'East/northeast Naxos beach inferred from coordinates. Treat north/east-sector wind as exposed.',
    }),
  },
  {
    islandTokens: ['naxos'],
    nameTokens: ['Hawaii'],
    profile: lowConfidenceNaxosProfile({
      beachFacingDirection: 250,
      shelterLevel: 'semi_sheltered',
      fetchExposure: 'medium',
      exposedToWindDirections: ['W', 'SW', 'NW'],
      notes: 'Southwest/west Naxos Alyko-area beach inferred from coordinates. Keep low confidence and avoid calm/protected claims.',
    }),
  },
];

const legacyOverrideEntriesFromOrder = (
  islandTokens: string[],
  firstLegacyId: number,
  names: Array<string | string[]>
): OverrideEntry[] => names
  .map((nameTokens, index) => {
    const profile = (windProfileOverridesByBeachId as Partial<Record<number, WindProfile>>)[firstLegacyId + index];
    return profile ? { islandTokens, nameTokens: Array.isArray(nameTokens) ? nameTokens : [nameTokens], profile } : undefined;
  })
  .filter((entry): entry is OverrideEntry => Boolean(entry));

const legacyParosOverrideEntries = legacyOverrideEntriesFromOrder(['paros'], 1817, [
  ['Agia Eirini', 'Agia Irini'], 'Agios Dimitrios', 'Agios Stefanos', 'Ampelas', ['Aspros Gkremos', 'Aspros Gremos'],
  'Voutakos', 'Glyfades', 'Delfini', 'Dryos', 'Kalogeros', 'Kolympithres', 'Krios',
  ['Laggeri', 'Langeri'], 'Livadia', 'Limnes', 'Logaras', 'Lolantonis', 'Martselo',
  'Mikri Santa Maria', 'Monastiri', 'Molos', 'Navtikos omilos Parou', 'Xyfara',
  'Paralia Agkali Chrysis Aktis', 'Paralia Alyki', 'Paralia Glyfa',
  ['Paralia Paroikias', 'Paralia Parikias'], 'Parasporos', 'Piperi', ['Poynta', 'Pounta'], 'Pyrgaki',
  'Santa Maria', ['Toyrkou Ammos', 'Tourkou Ammos'], 'Tserdakia (Nea Chrysi Akti)', 'Tsoukalia',
  ['Faraggas', 'Farangas'], 'Chrysi Akti',
]);

const legacyAndrosOverrideEntries = legacyOverrideEntriesFromOrder(['andros'], 1503, [
  'Ag.Kyprianos', 'Agios Ioannis', 'Agios Petros', 'Apothikes', 'Artemidi',
  'Ateni', 'Achla', 'Vitali', 'Vlychada', 'Vori', 'Vintzi', 'Gides', 'Gyalia',
  'Zorkos', 'Kalamitsi', 'Kaminaki', 'Kolona', ['Neimporio', 'Nimporio'], 'Kourtali',
  'Kypri', ['Leyka', 'Levka'], 'Lefkivari', 'Limanaki', 'Lydi', 'Megala Peza', 'Mikra Peza',
  'Mikrogiali', ['Mpatsi', 'Batsi'], ['Mpouros', 'Bouros'], 'Palaiopoli', ['Paralia Feloy', 'Paralia Felou'],
  'Paraporti', 'Piso Gyalia', 'Piso Limnionas', 'Platanistos', 'Pyrgos',
  'Rozos', 'Steno (Stavros)', 'Syneti', 'Tis grias to pidima', 'Chrysi Ammos',
]);

const overrideEntries: OverrideEntry[] = [
  ...legacyParosOverrideEntries,
  ...legacyAndrosOverrideEntries,
  ...legacyMilosOverrideEntries,
  ...milosPhase3CoverageOverrideEntries,
  ...naxosPhase1CoverageOverrideEntries,
  // 2026-06-11 Mykonos pass: the island runs entirely on geospatial backfill,
  // which cannot carry the known-wind-sport policy. Ftelia and Korfos are THE
  // two Mykonos kite/windsurf bays (verified: kitesurfy.com, bestkitespots.com,
  // letskite.ch) — conservative name overrides so the >=4 Bft wind-sport
  // warning and caps fire; facings match the high-res geometry.
  {
    islandTokens: ['mykonos', 'μυκονος', 'μυκονου'],
    nameTokens: ['Ftelia'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 2,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'NW'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Ftelia bay is the historic Mykonos windsurf/kite spot: the N/NNE meltemi blows fully onshore with open Aegean fetch (kitesurfy.com, surf-magazin.de). Facing matches the high-res geometry (2 deg).',
    }),
  },
  {
    islandTokens: ['mykonos', 'μυκονος', 'μυκονου'],
    nameTokens: ['Korfos'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 350,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'NE'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Korfos bay is the second Mykonos kite spot (beginner-friendly flat water in meltemi; kitesurfy.com, bestkitespots.com, letskite.ch). North-opening bay between the town and the airport; facing matches the high-res geometry (350 deg).',
    }),
  },
  // 2026-06-11 Santorini pass: same backfill gap as Mykonos — Monolithos is
  // the island's windsurf/kite school spot (NE meltemi 15-20+ knots; verified:
  // kiteforum.com, spots4kite.com, greeka.com/santorini/sports/kitesurfing).
  {
    islandTokens: ['santorini', 'σαντορινη', 'σαντορινης', 'thira'],
    nameTokens: ['Monolithos'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 53,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'E'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Monolithos hosts the Santorini windsurf/kite school: NE meltemi 15-20+ knots, wavy above 18 (kiteforum.com, spots4kite.com, greeka.com). East-coast beach by the airport; facing matches the high-res geometry (53 deg).',
    }),
  },
  // 2026-06-11 national wind-sport coverage pass: every entry verified at a
  // dedicated spot/center page (not search snippets). Facings match the
  // high-res geometry; exposure sectors come from the geometry exposed
  // sectors. Conservative low-confidence profiles — warnings/caps only.
  {
    islandTokens: ['rhodes', 'ροδος', 'ροδου'],
    nameTokens: ['Prasonisi'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 132,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['E', 'SE', 'S', 'W'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Prasonisi is one of the most famous wind capes in Europe — multiple windsurf/kite centers operate on the double-sided sand spit (prasonisicenter.com 32+ years, kiteprasonisi.com, prasonisi.com ProCenter). Meltemi accelerates over the cape May-October.',
    }),
  },
  {
    islandTokens: ['lefkada', 'λευκαδα', 'λευκαδας'],
    nameTokens: ['Vasiliki'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 199,
      shelterLevel: 'open',
      fetchExposure: 'medium',
      exposedToWindDirections: ['S', 'SE', 'SW'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Vasiliki bay is a world-renowned windsurf destination with resident clubs (Club Vass, Wildwind, Surf School Vasiliki — amazinglefkada.com guide). Strong thermal cross-shore wind every summer afternoon.',
    }),
  },
  {
    islandTokens: ['lefkada', 'λευκαδα', 'λευκαδας'],
    nameTokens: ['Agios Ioannis'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 326,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W', 'SW'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Agios Ioannis / Milos beach by Lefkada town is the island kite spot (milosbeach.gr resort, spots4kite.com, kiteforum.com): SW-W-NW thermals 12-24 knots daily, the only legal kite beach on Lefkada.',
    }),
  },
  {
    islandTokens: ['kos', 'κως', 'κω'],
    nameTokens: ['Marmari'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 340,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      knownWindSportSpot: true,
      localWindAmplification: 'medium',
      notes: 'Marmari is a named Kos kite/windsurf spot (kitesurfingkos.com, kiteworldwide.com school, fun2fun-kos.com): meltemi W-NW blows diagonally onshore over the long sandy beach.',
    }),
  },
  {
    islandTokens: ['kos', 'κως', 'κω'],
    nameTokens: ['Mastichari'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 329,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NW', 'W'],
      knownWindSportSpot: true,
      localWindAmplification: 'medium',
      notes: 'Mastichari hosts VDWS kite/windsurf schools on the wide north-coast beach (kitesurfingkos.com, horizonsurfing.com, kiteworldwide.com): constant meltemi over a 400 m launch zone.',
    }),
  },
  {
    islandTokens: ['kos', 'κως', 'κω'],
    nameTokens: ['Psalidi'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 337,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['NW', 'N', 'NE'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Psalidi has the strongest wind on Kos — dedicated kite/windsurf zone with rescue-boat schools (wakeupstoked.com spot guide, kitejungle.com Psalidi Windzone). Cross-offshore meltemi accelerates along the strait toward Turkey.',
    }),
  },
  {
    islandTokens: ['lemnos', 'limnos', 'λημνος', 'λημνου'],
    nameTokens: ['Keros'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 89,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['E', 'SE', 'NE'],
      knownWindSportSpot: true,
      localWindAmplification: 'medium',
      notes: 'Keros bay is the Lemnos kite/windsurf camp (surfclubkeros.com, sportif.travel Keros Bay camp): 3 km bay with flat water north / waves south under meltemi.',
    }),
  },
  {
    islandTokens: ['crete (lasithi)', 'lasithi', 'λασιθι'],
    nameTokens: ['Kouremenos'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 55,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['NE', 'E', 'N'],
      knownWindSportSpot: true,
      localWindAmplification: 'high',
      notes: 'Kouremenos bay at Palekastro is the east-Crete windsurf spot (Freak windsurf center — sportif.travel Crete Windsurf Centre): venturi-accelerated meltemi all season.',
    }),
  },
  {
    islandTokens: ['tinos', 'τηνος', 'τηνου'],
    nameTokens: ['Kolympithra', 'Kolymbithra'],
    profile: lowConfidenceDirectionalProfile({
      beachFacingDirection: 19,
      shelterLevel: 'open',
      fetchExposure: 'high',
      exposedToWindDirections: ['N', 'NE', 'NW'],
      knownWindSportSpot: true,
      localWindAmplification: 'medium',
      notes: 'Kolymbithra is the hub of the Tinos SURF scene (thesurfatlas.com): north-facing bay that catches meltemi swell — waves, not calm swimming, whenever the north wind runs.',
    }),
  },
  {
    islandTokens: ['paros', 'παρος', 'παρου'],
    nameTokens: ['χρυση ακτη', 'golden beach'],
    profile: windProfileOverridesByBeachId[1853],
  },
  {
    islandTokens: ['andros', 'ανδρος', 'ανδρου'],
    nameTokens: ['συνετι', 'syneti'],
    profile: windProfileOverridesByBeachId[1541],
  },
  {
    islandTokens: ['andros', 'ανδρος', 'ανδρου'],
    nameTokens: ['πισω γυαλια', 'piso gialia'],
    profile: windProfileOverridesByBeachId[1535],
  },
  {
    islandTokens: ['andros', 'ανδρος', 'ανδρου'],
    nameTokens: ['αποθηκες', 'apothikes'],
    profile: windProfileOverridesByBeachId[1506],
  },
];

const beachNameTokens = (beach: Pick<Beach, 'name' | 'aliases'>): string[] => [
  normalizeToken(beach.name?.en),
  normalizeToken(beach.name?.gr),
  ...(beach.aliases || []).map(normalizeToken),
].filter(Boolean);

const beachIslandTokens = (beach: Pick<Beach, 'location'>): string[] => [
  normalizeToken(beach.location?.island),
  normalizeToken(beach.location?.region),
].filter(Boolean);

const legacyOverrideOwnerById = (beachId: number): string | undefined => {
  if (beachId >= 1503 && beachId <= 1543) return 'andros';
  if (beachId >= 1727 && beachId <= 1759) return 'milos';
  if (beachId >= 1817 && beachId <= 1853) return 'paros';
  return undefined;
};

export const getWindProfileOverride = (
  beach: Pick<Beach, 'id' | 'name' | 'aliases' | 'location'>
): WindProfile | undefined => {
  const islands = beachIslandTokens(beach);
  const byId = windProfileOverridesByBeachId[beach.id];
  if (byId) {
    const legacyOwner = legacyOverrideOwnerById(beach.id);
    if (!legacyOwner || islands.includes(legacyOwner)) return byId;
  }

  const names = beachNameTokens(beach);

  return overrideEntries.find(entry => (
    entry.nameTokens.some(token => names.includes(normalizeToken(token))) &&
    entry.islandTokens.some(token => islands.includes(normalizeToken(token)))
  ))?.profile;
};
