import {
  getDestinationPhoto,
  type CuratedPhoto,
  type DestinationId,
  type DestinationPhotoType,
} from './photoRegistry';
import destinationStripPhotos from './destinationStripPhotos.generated.json';
import regionStripPhotos from './regionStripPhotos.generated.json';
import sourcedRegionStripPhotos from './sourcedRegionStripPhotos.generated.json';

const stripCropById = destinationStripPhotos as Record<
  string,
  { src: string; width: number; height: number }
>;

// Regions without a curated destination card but with a licensed background image — the
// background is cropped into a strip photo (with attribution) by scripts/buildRegionStripPhotos.mjs.
const regionStripById = regionStripPhotos as unknown as Record<string, CuratedPhoto>;

// Regions with no local photo at all, for which a representative free-licensed image was
// sourced from Wikimedia Commons by scripts/sourceRegionStripImages.mjs.
const sourcedStripById = sourcedRegionStripPhotos as unknown as Record<string, CuratedPhoto>;

const islandIdToDestinationPhotoId: Partial<Record<string, DestinationId>> = {
  'crete-crete-chania': 'crete',
  'crete-crete-heraklion': 'crete',
  'crete-crete-lasithi': 'crete',
  'crete-crete-rethymno': 'crete',
  'ionian-islands-corfu': 'corfu',
  'ionian-islands-kefalonia': 'kefalonia',
  'ionian-islands-lefkada': 'lefkada',
  'ionian-islands-zakynthos': 'zakynthos',
  'south-aegean-milos': 'milos',
  'south-aegean-mykonos': 'mykonos',
  'south-aegean-naxos': 'naxos',
  'south-aegean-paros': 'paros',
  'south-aegean-rhodes': 'rhodes',
  'south-aegean-santorini': 'santorini',
  'south-aegean-syros': 'syros',
  'south-aegean-andros': 'andros',
  'north-aegean-samos': 'samos',
  'thessaly-skiathos': 'skiathos',
  'thessaly-skopelos': 'skopelos',
  'east-macedonia-and-thrace-thasos': 'thasos',
  'central-macedonia-halkidiki-mainland': 'chalkidiki',
  'peloponnese-messinia-mainland': 'peloponnese',
  'peloponnese-lakonia-mainland': 'peloponnese',
  'peloponnese-argolida-mainland': 'peloponnese',
  'peloponnese-arkadia-mainland': 'peloponnese',
  'peloponnese-korinthia-mainland': 'peloponnese',
};

export const getIslandDestinationPhoto = (
  islandId: string,
  type: DestinationPhotoType,
): CuratedPhoto | undefined => {
  const destinationId = islandIdToDestinationPhotoId[islandId];
  if (!destinationId) {
    return undefined;
  }

  return getDestinationPhoto(destinationId, type);
};

/**
 * Photo used for the homepage context strip. Prefers the lighter, wide-short `*-strip.webp`
 * crop generated by scripts/optimizeStripImages.mjs (focal point baked in), falling back to
 * the dedicated `hero` or the `card`. Returns undefined for destinations with no photo.
 */
export const getIslandStripPhoto = (
  islandId: string,
): CuratedPhoto | undefined => {
  const source = getIslandDestinationPhoto(islandId, 'hero') ?? getIslandDestinationPhoto(islandId, 'card');
  if (source) {
    const destinationId = islandIdToDestinationPhotoId[islandId];
    const crop = destinationId ? stripCropById[destinationId] : undefined;
    // Keep the source's attribution/alt; swap in the lighter crop's src + dimensions and
    // drop the now-redundant objectPosition (the focal crop is baked into the strip image).
    return crop
      ? { ...source, src: crop.src, width: crop.width, height: crop.height, objectPosition: undefined }
      : source;
  }

  // Fallback: regions with a licensed background image (cropped to a strip), then a
  // representative image sourced from Wikimedia Commons for regions with no local photo.
  return regionStripById[islandId] ?? sourcedStripById[islandId];
};
