// AUTO-GENERATED by scripts/buildLandingHeroAssets.mjs — do not hand-edit.
// Re-run the script after replacing source photos in "C:\Users\Miltos\Desktop\landing page".

export type HeroSlot = 'morning' | 'afternoon' | 'evening';

export interface HeroVariant {
  width: number;
  avif: string;
  webp: string;
}

export interface HeroSlotSources {
  mobile: HeroVariant[];
  desktop: HeroVariant[];
}

export const HERO_SOURCES: Record<HeroSlot, HeroSlotSources> = {
  "morning": {
    "mobile": [
      {
        "width": 480,
        "avif": "/landing/morning-mobile-480-v2.avif",
        "webp": "/landing/morning-mobile-480-v2.webp"
      },
      {
        "width": 640,
        "avif": "/landing/morning-mobile-640-v2.avif",
        "webp": "/landing/morning-mobile-640-v2.webp"
      },
      {
        "width": 828,
        "avif": "/landing/morning-mobile-828-v2.avif",
        "webp": "/landing/morning-mobile-828-v2.webp"
      },
      {
        "width": 960,
        "avif": "/landing/morning-mobile-960-v2.avif",
        "webp": "/landing/morning-mobile-960-v2.webp"
      },
      {
        "width": 1200,
        "avif": "/landing/morning-mobile-1200-v2.avif",
        "webp": "/landing/morning-mobile-1200-v2.webp"
      },
      {
        "width": 1440,
        "avif": "/landing/morning-mobile-1440-v2.avif",
        "webp": "/landing/morning-mobile-1440-v2.webp"
      }
    ],
    "desktop": [
      {
        "width": 960,
        "avif": "/landing/morning-desktop-960-v2.avif",
        "webp": "/landing/morning-desktop-960-v2.webp"
      },
      {
        "width": 1280,
        "avif": "/landing/morning-desktop-1280-v2.avif",
        "webp": "/landing/morning-desktop-1280-v2.webp"
      },
      {
        "width": 1600,
        "avif": "/landing/morning-desktop-1600-v2.avif",
        "webp": "/landing/morning-desktop-1600-v2.webp"
      },
      {
        "width": 1920,
        "avif": "/landing/morning-desktop-1920-v2.avif",
        "webp": "/landing/morning-desktop-1920-v2.webp"
      },
      {
        "width": 2200,
        "avif": "/landing/morning-desktop-2200-v2.avif",
        "webp": "/landing/morning-desktop-2200-v2.webp"
      },
      {
        "width": 2560,
        "avif": "/landing/morning-desktop-2560-v2.avif",
        "webp": "/landing/morning-desktop-2560-v2.webp"
      }
    ]
  },
  "afternoon": {
    "mobile": [
      {
        "width": 480,
        "avif": "/landing/afternoon-mobile-480-v2.avif",
        "webp": "/landing/afternoon-mobile-480-v2.webp"
      },
      {
        "width": 640,
        "avif": "/landing/afternoon-mobile-640-v2.avif",
        "webp": "/landing/afternoon-mobile-640-v2.webp"
      },
      {
        "width": 828,
        "avif": "/landing/afternoon-mobile-828-v2.avif",
        "webp": "/landing/afternoon-mobile-828-v2.webp"
      },
      {
        "width": 960,
        "avif": "/landing/afternoon-mobile-960-v2.avif",
        "webp": "/landing/afternoon-mobile-960-v2.webp"
      },
      {
        "width": 1200,
        "avif": "/landing/afternoon-mobile-1200-v2.avif",
        "webp": "/landing/afternoon-mobile-1200-v2.webp"
      },
      {
        "width": 1440,
        "avif": "/landing/afternoon-mobile-1440-v2.avif",
        "webp": "/landing/afternoon-mobile-1440-v2.webp"
      }
    ],
    "desktop": [
      {
        "width": 960,
        "avif": "/landing/afternoon-desktop-960-v2.avif",
        "webp": "/landing/afternoon-desktop-960-v2.webp"
      },
      {
        "width": 1280,
        "avif": "/landing/afternoon-desktop-1280-v2.avif",
        "webp": "/landing/afternoon-desktop-1280-v2.webp"
      },
      {
        "width": 1600,
        "avif": "/landing/afternoon-desktop-1600-v2.avif",
        "webp": "/landing/afternoon-desktop-1600-v2.webp"
      },
      {
        "width": 1920,
        "avif": "/landing/afternoon-desktop-1920-v2.avif",
        "webp": "/landing/afternoon-desktop-1920-v2.webp"
      },
      {
        "width": 2200,
        "avif": "/landing/afternoon-desktop-2200-v2.avif",
        "webp": "/landing/afternoon-desktop-2200-v2.webp"
      },
      {
        "width": 2560,
        "avif": "/landing/afternoon-desktop-2560-v2.avif",
        "webp": "/landing/afternoon-desktop-2560-v2.webp"
      }
    ]
  },
  "evening": {
    "mobile": [
      {
        "width": 480,
        "avif": "/landing/evening-mobile-480-v2.avif",
        "webp": "/landing/evening-mobile-480-v2.webp"
      },
      {
        "width": 640,
        "avif": "/landing/evening-mobile-640-v2.avif",
        "webp": "/landing/evening-mobile-640-v2.webp"
      },
      {
        "width": 828,
        "avif": "/landing/evening-mobile-828-v2.avif",
        "webp": "/landing/evening-mobile-828-v2.webp"
      },
      {
        "width": 960,
        "avif": "/landing/evening-mobile-960-v2.avif",
        "webp": "/landing/evening-mobile-960-v2.webp"
      },
      {
        "width": 1200,
        "avif": "/landing/evening-mobile-1200-v2.avif",
        "webp": "/landing/evening-mobile-1200-v2.webp"
      },
      {
        "width": 1440,
        "avif": "/landing/evening-mobile-1440-v2.avif",
        "webp": "/landing/evening-mobile-1440-v2.webp"
      }
    ],
    "desktop": [
      {
        "width": 960,
        "avif": "/landing/evening-desktop-960-v2.avif",
        "webp": "/landing/evening-desktop-960-v2.webp"
      },
      {
        "width": 1280,
        "avif": "/landing/evening-desktop-1280-v2.avif",
        "webp": "/landing/evening-desktop-1280-v2.webp"
      },
      {
        "width": 1600,
        "avif": "/landing/evening-desktop-1600-v2.avif",
        "webp": "/landing/evening-desktop-1600-v2.webp"
      },
      {
        "width": 1920,
        "avif": "/landing/evening-desktop-1920-v2.avif",
        "webp": "/landing/evening-desktop-1920-v2.webp"
      },
      {
        "width": 2200,
        "avif": "/landing/evening-desktop-2200-v2.avif",
        "webp": "/landing/evening-desktop-2200-v2.webp"
      },
      {
        "width": 2560,
        "avif": "/landing/evening-desktop-2560-v2.avif",
        "webp": "/landing/evening-desktop-2560-v2.webp"
      }
    ]
  }
};

// Desktop band takes over at this breakpoint (matches Tailwind's `sm:`).
export const HERO_DESKTOP_MEDIA = '(min-width: 640px)';
